#!/usr/bin/env python3
"""Number of classes of S_m under the equivalence generated by the KNOWN Wilf-equivalence theorems:
   (S) the eight symmetries of the square (reverse, complement, inverse);
   (B) Backelin-West-Xin: 12..k (+) g  ~  k..21 (+) g   (shape-Wilf, hence right direct-sum extension);
   (W) Stankova-West:     231 (+) g  ~  312 (+) g;
   optionally (K) Stankova 1994: 1342 ~ 2413 (length 4 only, no extension known).
Usage: known_classes.py m [--with-1342]
Prints the number of classes and writes the classes to stdout-friendly file if -o given.
"""
import sys, itertools
from collections import defaultdict

def reverse(p): return tuple(reversed(p))
def complement(p):
    m=len(p); return tuple(m+1-x for x in p)
def inverse(p):
    m=len(p); q=[0]*m
    for i,x in enumerate(p): q[x-1]=i+1
    return tuple(q)
def symmetries(p):
    out=set(); q=p
    for _ in range(4):
        out.add(q); out.add(inverse(q)); q=reverse(complement(q)) if False else q
    # generate full D4
    res=set([p]); frontier=[p]
    while frontier:
        x=frontier.pop();
        for y in (reverse(x),complement(x),inverse(x)):
            if y not in res: res.add(y); frontier.append(y)
    return res

def dsum(a,b):
    return tuple(a)+tuple(x+len(a) for x in b)

def first_summand_len(p):
    """length of the shortest nonempty proper direct-sum prefix (0 if sum-indecomposable)."""
    m=len(p); mx=0
    for i in range(m-1):
        mx=max(mx,p[i])
        if mx==i+1: return i+1
    return 0

class UF:
    def __init__(s,n): s.p=list(range(n))
    def f(s,x):
        while s.p[x]!=x: s.p[x]=s.p[s.p[x]]; x=s.p[x]
        return x
    def u(s,a,b):
        a,b=s.f(a),s.f(b)
        if a!=b: s.p[a]=b

def main():
    m=int(sys.argv[1]); with1342='--with-1342' in sys.argv
    perms=list(itertools.permutations(range(1,m+1)))
    idx={p:i for i,p in enumerate(perms)}
    uf=UF(len(perms))
    for p in perms:
        for q in symmetries(p): uf.u(idx[p],idx[q])
        # decompose p = a (+) g for every proper direct-sum prefix a (all prefixes, not just the first)
        mx=0
        for i in range(m-1):
            mx=max(mx,p[i])
            if mx==i+1:
                a=p[:i+1]; g=tuple(x-(i+1) for x in p[i+1:])
                k=i+1
                if a==tuple(range(1,k+1)) and k>=2: uf.u(idx[p],idx[dsum(tuple(range(k,0,-1)),g)])
                if a==tuple(range(k,0,-1)) and k>=2: uf.u(idx[p],idx[dsum(tuple(range(1,k+1)),g)])
                if a==(2,3,1): uf.u(idx[p],idx[dsum((3,1,2),g)])
                if a==(3,1,2): uf.u(idx[p],idx[dsum((2,3,1),g)])
        if with1342 and m==4:
            if p==(1,3,4,2): uf.u(idx[p],idx[(2,4,1,3)])
    classes=defaultdict(list)
    for p in perms: classes[uf.f(idx[p])].append(p)
    print(m, len(classes))
    if '-o' in sys.argv:
        fn=sys.argv[sys.argv.index('-o')+1]
        with open(fn,'w') as f:
            for c in sorted(classes.values(), key=lambda c:min(c)):
                f.write(' '.join(''.join(map(str,p)) for p in sorted(c))+'\n')
main()
