#!/usr/bin/env python3
"""Provenance certificate for the Wilf classes of S_m generated by the known theorems.
For every class we output a spanning tree of 'moves', each move being one application of
  SYM:<name>  (reverse r, complement c, inverse i),
  BWX:<k>     (12..k (+) g  <->  k..21 (+) g,  Backelin-West-Xin with right direct-sum extension),
  SW          (231 (+) g  <->  312 (+) g,  Stankova-West with right direct-sum extension),
so that every member of the class is reached from the class representative (its smallest member).
Usage: provenance.py m outfile
Output format: one class per block:  'class <id> size <s> rep <rep>' then lines 'pattern <- pattern via MOVE'."""
import sys, itertools
if not __debug__: raise RuntimeError("Run without -O/PYTHONOPTIMIZE: assertions are verification checks")
from collections import defaultdict, deque
def reverse(p): return tuple(reversed(p))
def complement(p):
    m=len(p); return tuple(m+1-x for x in p)
def inverse(p):
    m=len(p); q=[0]*m
    for i,x in enumerate(p): q[x-1]=i+1
    return tuple(q)
def dsum(a,b): return tuple(a)+tuple(x+len(a) for x in b)
def moves(p):
    m=len(p); out=[(reverse(p),'SYM:r'),(complement(p),'SYM:c'),(inverse(p),'SYM:i')]
    mx=0
    for i in range(m-1):
        mx=max(mx,p[i])
        if mx==i+1:
            a=p[:i+1]; g=tuple(x-(i+1) for x in p[i+1:]); k=i+1
            if k>=2 and a==tuple(range(1,k+1)): out.append((dsum(tuple(range(k,0,-1)),g),f'BWX:{k}'))
            if k>=2 and a==tuple(range(k,0,-1)): out.append((dsum(tuple(range(1,k+1)),g),f'BWX:{k}'))
            if a==(2,3,1): out.append((dsum((3,1,2),g),'SW'))
            if a==(3,1,2): out.append((dsum((2,3,1),g),'SW'))
    return out
m=int(sys.argv[1]); out=sys.argv[2]
perms=list(itertools.permutations(range(1,m+1))); seen=set(); classes=[]
for p in perms:
    if p in seen: continue
    # BFS from the class minimum: first collect the class, then BFS from its minimum
    comp={p}; q=deque([p])
    while q:
        x=q.popleft()
        for y,_ in moves(x):
            if y not in comp: comp.add(y); q.append(y)
    rep=min(comp); parent={rep:None}; q=deque([rep])
    while q:
        x=q.popleft()
        for y,mv in moves(x):
            if y not in parent: parent[y]=(x,mv); q.append(y)
    assert set(parent)==comp
    classes.append((rep,parent)); seen|=comp
classes.sort()
stats=defaultdict(int)
with open(out,'w') as f:
    for cid,(rep,parent) in enumerate(classes,1):
        f.write(f"class {cid} size {len(parent)} rep {''.join(map(str,rep))}\n")
        for y in sorted(parent):
            if parent[y] is None: continue
            x,mv=parent[y]; stats[mv.split(':')[0]]+=1
            f.write(f"  {''.join(map(str,y))} <- {''.join(map(str,x))} via {mv}\n")
print("m =",m,"classes:",len(classes),"moves used:",dict(stats))
